// <auto-generated />
using System;
using Infra.Repositories.EF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Repositories.EF.Migrations
{
    [DbContext(typeof(EavContext))]
    [Migration("20241015165313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ancestry", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.HasKey("ClassId", "ParentId")
                        .HasName("PK__Ancestri__CF8260B6E108D3A6");

                    b.HasIndex("ParentId");

                    b.ToTable("Ancestries", (string)null);
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.AbstractPropertyDetail", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyID");

                    b.Property<string>("DeleteBehaviour")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Max")
                        .HasColumnType("int");

                    b.Property<int?>("Min")
                        .HasColumnType("int");

                    b.HasKey("PropertyId")
                        .HasName("PK__Relation__70C9A755AD2F208E");

                    b.HasIndex("DeleteBehaviour");

                    b.ToTable("AbstractPropertyDetails");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Types__3214EC27154A2D2D");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.DeleteBehaviour", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Name")
                        .HasName("PK__Deletion__737584F761214E1A");

                    b.ToTable("DeleteBehaviours");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.Object", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Entities__3214EC2769EAA14C");

                    b.HasIndex("ClassId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PropertyClassId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyClassID");

                    b.HasKey("Id")
                        .HasName("PK__Relation__3214EC27248D1913");

                    b.HasIndex("ClassId");

                    b.HasIndex("PropertyClassId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.StringValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObjectId")
                        .HasColumnType("int")
                        .HasColumnName("ObjectID");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyID");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__StringVa__3214EC2753E7643C");

                    b.HasIndex("ObjectId");

                    b.HasIndex("PropertyId");

                    b.ToTable("StringValues");
                });

            modelBuilder.Entity("Ancestry", b =>
                {
                    b.HasOne("Infra.Repositories.EF.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Ancestrie__TypeI__7CD98669");

                    b.HasOne("Infra.Repositories.EF.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .IsRequired()
                        .HasConstraintName("FK__Ancestrie__Paren__7DCDAAA2");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.AbstractPropertyDetail", b =>
                {
                    b.HasOne("Infra.Repositories.EF.Models.DeleteBehaviour", "DeleteBehaviourNavigation")
                        .WithMany("AbstractPropertyDetails")
                        .HasForeignKey("DeleteBehaviour")
                        .HasConstraintName("FK__RelationD__OnDel__0539C240");

                    b.HasOne("Infra.Repositories.EF.Models.Property", "Property")
                        .WithOne("AbstractPropertyDetail")
                        .HasForeignKey("Infra.Repositories.EF.Models.AbstractPropertyDetail", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RelationD__OnDel__04459E07");

                    b.Navigation("DeleteBehaviourNavigation");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.Object", b =>
                {
                    b.HasOne("Infra.Repositories.EF.Models.Class", "Class")
                        .WithMany("Objects")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Entities__TypeID__0A338187");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.Property", b =>
                {
                    b.HasOne("Infra.Repositories.EF.Models.Class", "Class")
                        .WithMany("PropertyClasses")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Relations__Origi__019E3B86");

                    b.HasOne("Infra.Repositories.EF.Models.Class", "PropertyClass")
                        .WithMany("PropertyPropertyClasses")
                        .HasForeignKey("PropertyClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Relations__Desti__02925FBF");

                    b.Navigation("Class");

                    b.Navigation("PropertyClass");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.StringValue", b =>
                {
                    b.HasOne("Infra.Repositories.EF.Models.Object", "Object")
                        .WithMany("StringValues")
                        .HasForeignKey("ObjectId")
                        .IsRequired()
                        .HasConstraintName("FK__StringVal__Entit__1F2E9E6D");

                    b.HasOne("Infra.Repositories.EF.Models.Property", "Property")
                        .WithMany("StringValues")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_StringValues_Attribute");

                    b.Navigation("Object");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.Class", b =>
                {
                    b.Navigation("Objects");

                    b.Navigation("PropertyClasses");

                    b.Navigation("PropertyPropertyClasses");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.DeleteBehaviour", b =>
                {
                    b.Navigation("AbstractPropertyDetails");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.Object", b =>
                {
                    b.Navigation("StringValues");
                });

            modelBuilder.Entity("Infra.Repositories.EF.Models.Property", b =>
                {
                    b.Navigation("AbstractPropertyDetail");

                    b.Navigation("StringValues");
                });
#pragma warning restore 612, 618
        }
    }
}
